apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "learnhub.configMapName" . }}
  labels:
    {{- include "learnhub.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.service.ports.api | quote }}
  ELASTICSEARCH_URL: {{ .Values.elasticsearch.url | quote }}
  POSTGRES_HOST: {{ .Values.postgres.host | quote }}
  POSTGRES_PORT: {{ .Values.postgres.port | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
