apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "learnhub.fullname" . }}-admin
  labels:
    {{- include "learnhub.componentLabels" (dict "root" . "component" "admin") | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.admin }}
  selector:
    matchLabels:
      {{- include "learnhub.componentLabels" (dict "root" . "component" "admin") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "learnhub.componentLabels" (dict "root" . "component" "admin") | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: admin
          image: "{{ .Values.images.admin.repository }}:{{ .Values.images.admin.tag }}"
          imagePullPolicy: {{ .Values.images.admin.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.ports.admin }}
          envFrom:
            - configMapRef:
                name: {{ include "learnhub.configMapName" . }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources.admin | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
