{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "learnhub.secretName" . }}
  labels:
    {{- include "learnhub.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.values }}
  {{ $key }}: {{ $val | toString | b64enc | quote }}
  {{- end }}
{{- end }}
