apiVersion: v1
kind: Service
metadata:
  name: {{ include "learnhub.fullname" . }}-api
  labels:
    {{- include "learnhub.componentLabels" (dict "root" . "component" "api") | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.api }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "learnhub.componentLabels" (dict "root" . "component" "api") | nindent 4 }}
